# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NodeLogViewer < Formula
  desc "New Relic log viewer for Node.js agent logs"
  homepage "https://github.com/newrelic/node-log-viewer"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/newrelic/node-log-viewer/releases/download/v0.2.0/nrlv_0.2.0_darwin_amd64.tar.gz"
      sha256 "c9034a213e9731d242cb2dbc34b83e59894e3136ce0dc8b25c5c6b5f7d0c6948"

      def install
        bin.install "nrlv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/newrelic/node-log-viewer/releases/download/v0.2.0/nrlv_0.2.0_darwin_arm64.tar.gz"
      sha256 "59ac768990bfc19a3649268e7c5ac4da815cf19e82ad23ec9e52fca1e9776dfa"

      def install
        bin.install "nrlv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/newrelic/node-log-viewer/releases/download/v0.2.0/nrlv_0.2.0_linux_amd64.tar.gz"
        sha256 "5724a6d6f87d74cd9ff799c9d1dbeaf4f41cc3f9ef205dd0253d70c1e5d2e13a"

        def install
          bin.install "nrlv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/newrelic/node-log-viewer/releases/download/v0.2.0/nrlv_0.2.0_linux_arm64.tar.gz"
        sha256 "e62e085ba87e7baaed819ccfb99344837e513e0376e521f88e27cef6e7523835"

        def install
          bin.install "nrlv"
        end
      end
    end
  end
end
